import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Button from "react-bootstrap/Button";
import Row from "react-bootstrap/Row";
import Col from "react-bootstrap/Row";
import Form from "react-bootstrap/Form";
import ListGroup from "react-bootstrap/ListGroup";
import Container from "react-bootstrap/Container";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container">
        <Row className="align-items-center">
          <Col>
            <h2>TODO LIST WEB3</h2>
          </Col>
        </Row>

        <Row>
          <div className="col col-md-6 col-xs-12">
            <Row className="mb-2">
              <div className="col-md-8 col-xs-12 px-0">
                <Form.Label htmlFor="inlineFormInput" visuallyHidden>
                  Name
                </Form.Label>
                <Form.Control id="inlineFormInput" placeholder="Jane Doe" />
              </div>
              <div className="col-md-4 col-xs-12 d-grid gap-3">
                <Button type="submit" className="mb-2">
                  Submit
                </Button>
              </div>
            </Row>
            <Row>
              <Col xs={12}>
                <ListGroup>
                  <ListGroup.Item>Dapibus ac facilisis in</ListGroup.Item>
                  <ListGroup.Item>Morbi leo risus</ListGroup.Item>
                  <ListGroup.Item>Porta ac consectetur ac</ListGroup.Item>
                </ListGroup>
              </Col>
            </Row>
          </div>
        </Row>
      </main>

      <footer className="footer mt-auto py-3 bg-light">
        <Container>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{" "}
            <span className={styles.logo}>
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
              />
            </span>
          </a>
        </Container>
      </footer>
    </>
  );
};

export default Home;
